### ISSUE TITLE
Updating props

### ISSUE THREAD

**Issue by JulianAnthes** [joshjg/react-canvas-knob#11]
Hi there,

I'm currently trying to implement this into a responsive page, but once the knob is rendered the first time, I'm unable to update the width/heights, because they are only set once (inside the constructor).

Is there a implementation of `componentWillReceiveProps()` on the road map or a `Pull Request` of this feature already there?
If not, I'm willing to implement this feature, if you want. 🍻

**Comment by JulianAnthes** [comment]
Just wrote a little pull request which implements `componentWillReceiveProps` for width & height. 😄

**Comment by joshjg** [comment]
Merged PR-12
